/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CodeWebCard: typeof import('./src/components/code-web-card/CodeWebCard.vue')['default']
    CommodityCardV1: typeof import('./src/components/commodity-card-v1/CommodityCardV1.vue')['default']
    DetailSection: typeof import('./src/components/detail-section/DetailSection.vue')['default']
    GoodPostBlock: typeof import('./src/components/good-post-block/GoodPostBlock.vue')['default']
    OurStoryCard: typeof import('./src/components/our-story-card/OurStoryCard.vue')['default']
    PostBlock: typeof import('./src/components/post-block/PostBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopInfoCard: typeof import('./src/components/shop-info-card/ShopInfoCard.vue')['default']
    SvgIcon: typeof import('./src/components/svg-icon/SvgIcon.vue')['default']
    TabBar: typeof import('./src/components/tab-bar/TabBar.vue')['default']
    TopbarHeadV1: typeof import('./src/components/topbar-head-v1/TopbarHeadV1.vue')['default']
    TopBarMain: typeof import('./src/components/top-bar-main/TopBarMain.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCircle: typeof import('vant/es')['Circle']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanProgress: typeof import('vant/es')['Progress']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
