/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CodeWebCard: typeof import('./src/components/code-web-card/CodeWebCard.vue')['default']
    CommodityCardV1: typeof import('./src/components/commodity-card-v1/CommodityCardV1.vue')['default']
    CommodityCardV2: typeof import('./src/components/commodity-card-v2/CommodityCardV2.vue')['default']
    CpPaySheet: typeof import('./src/components/cp-pay-sheet/CpPaySheet.vue')['default']
    DetailSection: typeof import('./src/components/detail-section/DetailSection.vue')['default']
    GoodPostBlock: typeof import('./src/components/good-post-block/GoodPostBlock.vue')['default']
    OurStoryCard: typeof import('./src/components/our-story-card/OurStoryCard.vue')['default']
    PostBlock: typeof import('./src/components/post-block/PostBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopInfoCard: typeof import('./src/components/shop-info-card/ShopInfoCard.vue')['default']
    SvgIcon: typeof import('./src/components/svg-icon/SvgIcon.vue')['default']
    TabBar: typeof import('./src/components/tab-bar/TabBar.vue')['default']
    TopbarHeadV1: typeof import('./src/components/topbar-head-v1/TopbarHeadV1.vue')['default']
    TopBarMain: typeof import('./src/components/top-bar-main/TopBarMain.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    'VanCell-': typeof import('vant/es')['Cell-']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCircle: typeof import('vant/es')['Circle']
    VanCol: typeof import('vant/es')['Col']
    VanCouponCell: typeof import('vant/es')['CouponCell']
    VanCouponList: typeof import('vant/es')['CouponList']
    VanField: typeof import('vant/es')['Field']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanForm: typeof import('vant/es')['Form']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanRow: typeof import('vant/es')['Row']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
